### PR TITLE
LDAPImport start_tls

### PR DESCRIPTION
**Pull request by wheldom01**
Patch adds support for the use of Net::LDAP start_tls to the LDAPImport.

### CODE REVIEW

**Comment by sunnavy** [comment]
Sorry for the late response.

I have 2 main concerns:

* it looks like Net::LDAP::start_tls accepts hash instead of hashref

but in your code:

    $msg = $ldap->start_tls( $RT::LDAPTLS );

I'm wondering if it works.

* $msg returned by start_tls isn't checked

We probably need to check it to see if there are any errors, just like the way we check $ldap->bind.

Thanks!

**Comment by wheldom01** [comment]
Hi,

No problem, I'll take a look as this this evening as it is a while since 
I wrote this patch.

Best Regards

Martin

**Comment by tobiasbp** [comment]
It would be great if this could be completed and merged in. Thanks.

**Comment by tobiasbp** [comment]
Is this change compatible with RT 4.4.4? This is the message I receive when running it:
`Unable to run rt-ldapimport without dependencies.
Rerun configure with the --enable-externalauth option`

**Comment by wheldom01** [comment]
Hi,

I believe that it should still be compatible, but can't confirm that as 
I'm not running 4.4.4 yet.
Could you confirm that the LDAPTLS variable is set correctly?

Set($LDAPTLS, {
     'verify'            =>  'require',
     'cafile'            =>  '/etc/ssl/certs/CACert.pem', } );  # Path CA 
file

I'll try to test it over the weekend.

Best Regards

Martin

**Comment by wheldom01** [comment]
Hi,

You will need the following modules installed to.

Crypt::SSLeay
IO::Socket::SSL
Net::SSLeay

Best Regards

Martin

**Comment by cbrandtbuffalo** [comment]
In 4c288fce, we ended up modifying LDAPImport to allow passing any arguments supported by Net::LDAP, so this is now covered. We also added TLS options to the example so it's clear how to configure a secure connection. This is available in RT 4.4.4 and newer, including RT 5.

Thanks for opening a PR and suggesting the improvement!

**Pull request closed without merging**
