### PR TITLE
SelectDate: Disable autocomplete for datepicker

### PR DESCRIPTION
**Pull request by mxhash**
Otherwise the autocomplete overlays the datepicker

screen shot 2018-09-06 at 10 29 50

### CODE REVIEW

**Comment by dnsmichi** [comment]
I've seen this today too, while working on a due date search filter in [this extension](https://github.com/NETWAYS/rt-extension-searchresult).

# Version

RT 4.4.3 4df308e

# Problem

screen shot 2019-01-15 at 15 58 38

# Fix

The fix in this PR solved the problem for me.

screen shot 2019-01-15 at 16 01 21

@sunnavy can you please have a look and merge this? Thanks :-)

**Comment by sunnavy** [comment]
Thanks for the commit, and it's a sane change to me. To make it 100% correct to be merged, could you do the following 2 more things?

* Apply the same change to other datepicker inputs in RT source, I can see that we have 2 more in share/html/Approvals/Elements/PendingMyApproval

* Create the branch off 4.4-trunk instead of master, according to our hacking doc: https://docs.bestpractical.com/rt/4.4.4/hacking.html

Thank you!

**Comment by mxhash** [comment]
OK, I changed the base and added the rest of the controls into the commit.

```
$ grep -r datepicker . | grep -v autocomplete
$ 
```

Cheers,
Marius

**Comment by sunnavy** [comment]
Merged to 4.4-trunk, thank you!

**Pull request closed without merging**
