### PR TITLE
Improve REST handling of txn CFs

### PR DESCRIPTION
**Pull request by sartak**
http://lists.bestpractical.com/pipermail/rt-devel/2016-March/012530.html

### CODE REVIEW

**Comment by djzort** [comment]
please merge this

**Comment by djzort** [comment]
Had to nuke the mason cache after watching my 4.4.2 install but seems to work perfectly.

**Comment by puck** [comment]
This is a duplicate of my PR #178. Naturally I'd like either this one, or that one to be merged. ;)

**Comment by djzort** [comment]
Seems like an obvious feature to pull in. Not sure why its delayed.

**Comment by puck** [comment]
Looks like my rebasing has confused this PR. Probably better to grab #178 .

**Pull request closed without merging**
